blank_issues_enabled: false
contact_links:
  - name: Report a bug or request a feature for Music Assistant Queue Actions
    url: https://github.com/droans/mass_queue/issues
    about: Issues with Queue Actions needs to be reported in its repository.